{
	"version": 1755074375,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/lv1_color-sheet0.png",
		"images/lv1_color-sheet1.png",
		"images/ellipse-sheet0.png",
		"images/ellipse-sheet1.png",
		"images/spritefont13.png",
		"images/frame-sheet0.png",
		"images/frame2-sheet0.png",
		"images/frame3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}